=head1 NAME

Amon::Manual::HandleStaticFile.ja - Amon で静的ファイルを扱う

=head1 チュートリアル

Amon::Manual::Tutorial.jaで作成した、Helloというアプリケーションを元に作成してみましょう。

=head2 CSSを読み込めるようにする

ディレクトリを作成します。

    $ mkdir -p htdocs/static/css/

今作成した、ディレクトリの中にcssを作成してみましょう。

    body {
        width: 800px;
        margin: 0px auto;
        border: solid 1px #00f;
    }

次にHello.psgiを以下のように編集します

   use Hello;
   use Hello::Web;
   
   use Plack::Builder;
   
   my $app = Hello::Web->app("./");
   builder {
       enable "Static", path => qr!^/static!, root => './htdocs';
       $app;
   }

次にtmpl/base.mtからcssにlinkしましょう

    <!doctype html>
    <html>
    <head>
    <link rel="stylesheet" type="text/css" href="/static/css/amon.css" />
    <title><? block title => 'Amon' ?></title>
    </head>
    <body>
    <? block content => 'body here' ?>
    </body>
    </html>

そして前回と同じく L<plackup> コマンドを利用し起動しましょう。

  $ plackup Hello.psgi
  Plack::Server::Standalone: Accepting connections at http://0:5000/

さて http://localhost:5000/ をみてみましょう。
これで画像やCSSやJavascriptも使えますね。

=cut
