=head1 NAME

Amon::Manual::Intro.ja - Amon への導入

=head1 DESCRIPTION

Amon 特徴は以下のとおり

=over 4

=item L<PSGI>対応

今はやりの L<PSGI> に対応しています。

=item XS への依存なし

pure perl のモジュールだけで構成されているので、XS がつかえない環境でも安心。

=item 薄いレイヤー

Amon は Model の制約などは導入しません。自由です。

=item Web に関係ある部分とそうじゃない部分の分離

Config や Model のまわりは単独のスクリプト等からも容易に利用できるようになっています。

=item めんどくさいのは嫌

本質的なアプリケーションの関心事に注力できるようにつくっています。

=back

=cut

