=head1 NAME

Amon::Manual::Mobile.ja - Amon でケータイ対応

=head1 DESCRIPTION

Amon でサックリとケータイ対応する方法についての解説です。

=head1 HOW TO ADD MOBILE PHONE SUPPORT

=head2 HTTP::MobileAgent との連携

L<Amon::Plugin::MobileAgent> を利用してください。利用方法は以下のとおり。

    package MyApp::Web;
    use Amon::Web -base => (
        default_view_class => 'MT',
    );
    __PACKAGE__->load_plugins(
        qw/ MobileAgent /
    );
    1;

=head2 Encode::JP::Mobile との連携

絵文字を扱うには L<Encode::JP::Mobile> をつかうとよいでしょう。HTML のエンコーディ
ングと Content-Type を以下のように設定しましょう。

    package MyApp::Web;
    use Amon::Web -base;

    __PACKAGE__->load_plugins('MobileCharset' => {});

=head2 CSS のインライン化

TBD

=head2 セッション

TBD

=head2 画像

TBD

=cut

