=head1 NAME

Amon::Manual::Tutorial.ja - Amon 日本語チュートリアル

=head1 チュートリアル

=head2 インストール

以下のコマンドを入力することによりインストールできます。

  git clone git://github.com/tokuhirom/Amon.git
  cd Amon
  perl Makefile.PL
  make installdeps
  make install

=head2 ハローワールド

まずは、アプリケーションの雛形を作成します。

  $ amon-setup.pl Hello
  $ cd Hello

雛形のディレクトリ構造は以下のようになっています。非常にシンプルでわかりやすい構造です。

    Hello
    |-- Hello.psgi
    |-- Makefile.PL
    |-- lib
    |   |-- Hello
    |   |   |-- M
    |   |   |-- V
    |   |   |   |-- MT
    |   |   |   |   `-- Context.pm
    |   |   |   `-- MT.pm
    |   |   |-- Web
    |   |   |   |-- C
    |   |   |   |   `-- Root.pm
    |   |   |   `-- Dispatcher.pm
    |   |   `-- Web.pm
    |   `-- Hello.pm
    |-- t
    |   `-- 01_root.t
    `-- tmpl
        |-- base.mt
        `-- index.mt

Amon のアプリケーションを起動させるには L<plackup> コマンドを利用します。

  $ plackup Hello.psgi
  Plack::Server::Standalone: Accepting connections at http://0:5000/

とうちこめば、もう http://localhost:5000/ にウェブサーバーがたちあがっているはずです。
なんという簡単さ！

=cut
