=encoding utf-8

=head1 NAME

Amon2::Manual::HandleStaticFile.ja - Amon2 で静的ファイルを扱う

=head1 チュートリアル

Amon2::Manual::Tutorial.jaで作成した、Helloというアプリケーションを元に作成してみましょう。

=head2 CSSを読み込めるようにする

Amon2 では、静的なコンテンツは htdocs/static/ に配置することになっています。
静的コンテンツは Plack::Middleware::Static により配信されます。

CSS は htdocs/static/css/ におきます。
デフォルトでは main.css という CSS がよみこまれます。このファイルを編集してみましょう。

    body {
        width: 800px;
        margin: 0px auto;
        border: solid 1px #00f;
    }

そして前回と同じく L<plackup> コマンドを利用し起動しましょう。

  $ plackup Hello.psgi
  Plack::Server::Standalone: Accepting connections at http://0:5000/

さて http://localhost:5000/ をみてみましょう。
これで画像やCSSやJavascriptも使えますね。

=cut
