#!/usr/bin/perl
use strict;
use warnings;
use utf8;
use 5.008001;
use LWP::UserAgent;
use autodie;
use Data::Dumper;
use File::Basename;

my $ua = LWP::UserAgent->new();

&main;exit;

sub main {
    run_jquery();
}

sub run_jquery {
    my $url = 'http://code.jquery.com/jquery-1.5.1.min.js';
    my $res = $ua->get($url);
    $res->is_success or die "Cannot fetch $url: " . $res->status_line;

    local $Data::Dumper::Terse = 1;
    my $jquery = $res->decoded_content;
    open my $fh, '>:utf8', 'lib/Amon2/Setup/Asset/jQuery.pm';
    print {$fh} sprintf(<<"...", Dumper(basename($url)), Data::Dumper::Dumper($jquery));
# This file is generated by $0. Do not edit manually.
package Amon2::Setup::Asset::jQuery;
use strict;
use warnings;

sub jquery_min_basename { %s }

sub jquery_min_content {
    %s
}

1;
...
    close $fh;
}


